//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace HRMS.Module.BusinessObjects.HRMS
{

    public partial class Employees : XPCustomObject
    {
        string fEmpId;
        /// <summary>
        /// test empid
        /// </summary>
        [Key]
        [DbType("varchar(10)")]
        public string EmpId
        {
            get { return fEmpId; }
            set { SetPropertyValue<string>(nameof(EmpId), ref fEmpId, value); }
        }
        string fEmpName;
        public string EmpName
        {
            get { return fEmpName; }
            set { SetPropertyValue<string>(nameof(EmpName), ref fEmpName, value); }
        }
    }

}
